name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:       # Allows manual triggering

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Needed to push changes
    
    steps:
      # Checkout the repository with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get full commit history for contributions
        
      # Create output directory
      - name: Create output directory
        run: mkdir -p dist
        
      # Generate the snake graphic
      - name: Generate contribution snake
        uses: platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
        
      # Verify the files were created
      - name: Verify files
        run: |
          ls -la dist/
          [ -f dist/github-contribution-grid-snake.gif ] || exit 1
          [ -f dist/github-contribution-grid-snake.svg ] || exit 1
        
      # Configure git
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      # Push to output branch (simplified version)
      - name: Push to output branch
        run: |
          git checkout -b output || git checkout output
          git add dist/
          git commit -m "Update contribution snake [auto]" || echo "No changes to commit"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ./  # Puts files at root of gh-pages
