name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Exécuté toutes les 12 heures
  workflow_dispatch:  # Permet l'exécution manuelle depuis l'interface GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake Animation
    
    steps:
      # Checkout du code
      - uses: actions/checkout@v2
      
      # Génération de l'animation Snake (versions claire et sombre)
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MOUHAMEDBOUZAYAN  # Ton nom d'utilisateur GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_out_path_dark: dist/github-contribution-grid-snake-dark.svg
      
      # Déploiement sur la branche output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Les fichiers seront poussés sur cette branche
          build_dir: dist        # Dossier contenant les fichiers à déployer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token d'authentification
