name: Generate Contribution Snake

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  # Allows manual triggering
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to get git history for contribution graph
        
      # Generate the snake graphic
      - name: Generate contribution snake
        uses: platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}  # Uses the repo owner's name automatically
          gif_out_path: snake/github-contribution-grid-snake.gif
          svg_out_path: snake/github-contribution-grid-snake.svg
          
      # Verify the files were created
      - name: List generated files
        run: |
          ls -la snake/
          
      # Configure git (needed for committing)
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      # Commit and push the generated files
      - name: Commit and push generated files
        run: |
          git add snake/
          git commit -m "Update contribution snake [skip ci]" || echo "No changes to commit"
          git push
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./snake
          keep_files: false  # Cleans the directory before deployment
